; ____       _       _
;|  _ \ ___ | |_   _| |__   __ _ _ __
;| |_) / _ \| | | | | '_ \ / _` | '__|  z0mbi3
;|  __/ (_) | | |_| | |_) | (_| | |     https://github.com/gh0stzk/dotfiles
;|_|   \___/|_|\__, |_.__/ \__,_|_|     z0mbi3.zk@protonmail.com
;               |___/

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ../../config/system.ini
include-file = modules.ini

[color]
bg = #1b1918
fg = #c6c5c5

mbg = #c6c5c5
red = #764d42
pink = #764d42
purple = #c28172
blue = #966664
blue-arch = #966664
cyan = #e2a98d
teal = #966664
green = #755459
lime = #755459
yellow = #8d603e
amber = #8d603e
orange = #764d42
brown = #764d42
grey = #966664
indigo = #966664
blue-gray = #1b1918

[bar/brenda]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 98%
height = 23

offset-x = 1%
offset-y = 5

background = ${color.bg}
foreground = ${color.fg}

radius = 1

line-size = 2
line-color = ${color.blue}

border-size = 10px
border-color = ${color.bg}

padding = 1

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = "JetBrainsMono:style=Bold:size=9;2"
; Icons
font-1 = "Font Awesome 6 Free Solid:size=10;3"
font-2 = "Material Design Icons Desktop:size=11;3"
font-3 = "Material Design Icons Desktop:size=12;3"
;dpi = 96

;Modules availables but not active:
;	brightness xkeyboard
modules-left = launcher bspwm sep cpu_bar sep memory_bar sep filesystem sep mpd_control sep weather
modules-center =
modules-right = bluetooth sep usercard mplayer sep battery sep network sep pulseaudio sep updates sep date sep tray sep power

separator =
dim-value = 1.0

;;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
