; ____       _       _
;|  _ \ ___ | |_   _| |__   __ _ _ __
;| |_) / _ \| | | | | '_ \ / _` | '__|  z0mbi3
;|  __/ (_) | | |_| | |_) | (_| | |     https://github.com/gh0stzk/dotfiles
;|_|   \___/|_|\__, |_.__/ \__,_|_|     z0mbi3.zk@protonmail.com
;               |___/

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ../../config/system.ini
include-file = modules.ini
include-file = ash_modules.ini

[color]
grad5 = #b0cd98
grad4 = #bdab75
grad3 = #8aac53
grad2 = #428a59
grad1 = #726127
redb = #CAB365
blackb = #b7b7b7
bg = #f4f4f4
bg-alt = #00f4f4f4
fg = #3d3d3d

trans = #00f4f4f4
white = #3d3d3d
black = #f4f4f4

red = #CAB365
pink = #CAB365
purple = #B7C6AB
blue = #C9BB92
cyan = #D1CEB3
teal = #C9BB92
green = #7A9984
lime = #b7b7b7
yellow = #A6B293
amber = #A6B293
orange = #CAB365
brown = #b7b7b7
grey = #f4f4f4
indigo = #b7b7b7
blue-gray = #b7b7b7

[bar/cristina-bar]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = true
fixed-center = false

width = 100%:-40
height = 20

offset-x = 20
offset-y = 20

background = ${color.bg}
foreground = ${color.fg}

radius-bottom = 1

line-size = 3
line-color = ${color.blue}

border-size = 14
border-color = ${color.bg}

padding-left = 2
padding-right = 1

module-margin-left = 0
module-margin-right = 0

font-0 = "JetBrainsMono:style=Bold:pixelsize=9;2"
font-1 = "Material Design Icons Desktop:size=13;3"
font-2 = "Font Awesome 6 Free Solid:size=10;3"
font-3 = "MesloLGS NF:style=Regular:size=13;3"

;Modules availables but not active:
;	brightness		weather		xkeyboard
modules-left = launcher sep2 bspwm sep2 title
modules-center =
modules-right = mpd2 sep tasks sep gmail workrave sep g4i loadavg g4d docker sep g3i network g3d sep g3i ping g3d updates2 sep g3i keyboard g3d sep g2i pulseaudio g2d sep g2i battery g2d bluetooth2 sep g2i usercard g2d sep g1i date g1d sep ahi tray ahd traytoggle sep power

separator =
dim-value = 1.0
;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
