; ____       _       _
;|  _ \ ___ | |_   _| |__   __ _ _ __
;| |_) / _ \| | | | | '_ \ / _` | '__|  z0mbi3
;|  __/ (_) | | |_| | |_) | (_| | |     https://github.com/gh0stzk/dotfiles
;|_|   \___/|_|\__, |_.__/ \__,_|_|     z0mbi3.zk@protonmail.com
;               |___/

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ../../config/system.ini
include-file = modules.ini
include-file = ash_modules.ini

[color]
redb = #B7AE6A
blackb = #b7b7b7
bg = #f4f4f4
bg-alt = #00f4f4f4
fg = #3d3d3d

trans = #00f4f4f4
white = #3d3d3d
black = #f4f4f4

red = #B7AE6A
pink = #B7AE6A
purple = #91799A
blue = #586393
cyan = #629CC8
teal = #586393
green = #EA9966
lime = #b7b7b7
yellow = #375FA3
amber = #375FA3
orange = #B7AE6A
brown = #b7b7b7
grey = #f4f4f4
indigo = #b7b7b7
blue-gray = #b7b7b7

[bar/cristina-bar]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = true
fixed-center = false

width = 95%
height = 20

offset-x = 2.5%
offset-y = 5

background = ${color.bg}
foreground = ${color.fg}

radius-bottom = 1

line-size = 3
line-color = ${color.blue}

border-size = 14
border-color = ${color.bg}

padding-left = 2
padding-right = 1

module-margin-left = 0
module-margin-right = 0

font-0 = "JetBrainsMono:style=Bold:pixelsize=9;2"
font-1 = "Material Design Icons Desktop:size=13;3"
font-2 = "Font Awesome 6 Free Solid:size=10;3"
font-3 = "MesloLGS NF:style=Regular:size=13;3"

;Modules availables but not active:
;	brightness		weather		xkeyboard
modules-left = launcher sep2 bspwm sep2 title
modules-center =
modules-right = ari mpd2 ard sep ayi tasks ayd sep agi gmail agd sep ati loadavg atd sep aai docker aad sep abi network abd api ping apd sep ari updates ard ayi keyboard ayd agi pulseaudio agd ati battery atd sep azi bluetooth usercard mplayer azd sep abi date abd sep ahi tray ahd traytoggle sep power

separator =
dim-value = 1.0
;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
