; ____       _       _
;|  _ \ ___ | |_   _| |__   __ _ _ __
;| |_) / _ \| | | | | '_ \ / _` | '__|  z0mbi3
;|  __/ (_) | | |_| | |_) | (_| | |     https://github.com/gh0stzk/dotfiles
;|_|   \___/|_|\__, |_.__/ \__,_|_|     z0mbi3.zk@protonmail.com
;               |___/

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ../../config/system.ini
include-file = modules.ini
include-file = ash_modules.ini

[color]
grad5 = #888482
grad4 = #767372
grad3 = #656261
grad2 = #535251
grad1 = #414141
redb = #666f78
blackb = #b7b7b7
bg = #f5f5f5
bg-alt = #00f5f5f5
fg = #3d3d3d

trans = #00f5f5f5
white = #3d3d3d
black = #f5f5f5

red = #666f78
pink = #666f78
purple = #9da2ac
blue = #95908e
cyan = #afadb0
teal = #95908e
green = #ce5051
lime = #b7b7b7
yellow = #76828c
amber = #76828c
orange = #666f78
brown = #b7b7b7
grey = #f5f5f5
indigo = #b7b7b7
blue-gray = #b7b7b7

[bar/cristina-bar]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = true
fixed-center = false

width = 100%:-40
height = 20

offset-x = 20
offset-y = 20

background = ${color.bg}
foreground = ${color.fg}

radius-bottom = 1

line-size = 3
line-color = ${color.blue}

border-size = 14
border-color = ${color.bg}

padding-left = 2
padding-right = 1

module-margin-left = 0
module-margin-right = 0

font-0 = "JetBrainsMono:style=Bold:pixelsize=9;2"
font-1 = "Material Design Icons Desktop:size=13;3"
font-2 = "Font Awesome 6 Free Solid:size=10;3"
font-3 = "MesloLGS NF:style=Regular:size=13;3"

;Modules availables but not active:
;	brightness		weather		xkeyboard
modules-left = launcher sep2 bspwm sep2 title
modules-center =
modules-right = mpd2 sep tasks sep gmail workrave sep g4i loadavg g4d docker sep g3i network g3d sep g3i ping g3d updates2 sep g3i keyboard g3d sep g2i pulseaudio g2d sep g2i battery g2d bluetooth2 sep g2i usercard g2d sep g1i date g1d sep ahi tray ahd traytoggle sep power

separator =
dim-value = 1.0
;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
