; ____       _       _
;|  _ \ ___ | |_   _| |__   __ _ _ __
;| |_) / _ \| | | | | '_ \ / _` | '__|  z0mbi3
;|  __/ (_) | | |_| | |_) | (_| | |     https://github.com/gh0stzk/dotfiles
;|_|   \___/|_|\__, |_.__/ \__,_|_|     z0mbi3.zk@protonmail.com
;               |___/

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ../../config/system.ini
include-file = modules.ini

[color]
bg = #f9f9fa
fg = #3e3e3e

red = #65696e
pink = #afb2b7
purple = #3e3e3e
blue = #db959a
blue-arch = #db959a
cyan = #b3b7ba
green = #696e73
yellow = #989ba0
lavander = #3e3e3e
amber = #65696e
orange = #65696e
brown = #afb2b7
grey = #bababb
indigo = #3e3e3e
blue-gray = #f9f9fa

[bar/dani]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 100%
height = 45

offset-x = 0
offset-y = 0

background = ${color.bg}
foreground = ${color.fg}

radius = 0

line-size = 2
line-color = ${color.blue}

border = 0
border-color = ${color.pink}

padding = 4

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = "Bebas Neue:style=Regular:size=13;3"
; Icons
font-1 = "Font Awesome 6 Free Solid:size=9;2"
font-2 = "Bebas Neue:style=Regular:size=15;3"
font-3 = "Material Design Icons Desktop:size=17;4"
; Glyphs
font-4 = "Bebas Neue:style=Regular:size=12;3"
font-5 = "Material Design Icons Desktop:size=11;2"
;dpi = 96

;Modules availables but not active:
;	brightness		xkeyboard
modules-left = launcher sep sep cpu_bar sep memory_bar sep filesystem sep weather sep tray
modules-center = bspwm
modules-right = mplayer usercard power bluetooth sep mpd_control sep battery sep network sep pulseaudio sep updates sep date

separator = "  "
dim-value = 1.0

;;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
